### ISSUE TITLE
lack of @v1 tag

### ISSUE THREAD

**Issue by tvardy** [alinz/ssh-scp-action#1]
I'm using the @latest tag, based on the documentation, but it's always loading the whole Docker image and steals around 30-60s of the whole workflow time... I think it would get cached in the worker if there was the @v1 tag available

**Comment by alinz** [comment]
Thanks @tvardy. I have tagged the latest version.

here's a example:

```
- name: SSH and SCP Setup
  uses: alinz/ssh-scp-action@v0.1.2
```

I'm closing this, but please feel free to open it again if that doesn't work for you

**Comment by tvardy** [comment]
Unfortunately it didn't work for the expected caching of the Docker image :( So it's probably something I could try to investigate further and raise as an issue for the GitHub Actions Team...

Anyways... using the semantic versioning is a wise idea... so I'm now secured if you're going to publish a v2 anytime in the future :D
